### ISSUE TITLE
createSku not working

### ISSUE THREAD

**Issue by masaok** [bigcommerce/bigcommerce-api-php#105]
I've tried both the static createSku and Sku->create() methods, but they both hang.

First, I modified Connection.php to print some debug output:
```
        curl_setopt($this->curl, CURLOPT_VERBOSE, true);
        curl_setopt($this->curl, CURLOPT_FAILONERROR, true);
print "CURL EXEC now...\n";
        curl_exec($this->curl);
print "CURL EXEC OK...\n";
```

Here's the output...
```
CURL EXEC NOW...
* Found bundle for host www.myhost.com: 0x2a388f0
* Re-using existing connection! (#0) with host www.myhost.com
* Connected to www.myhost.com (192.200.171.10) port 443 (#0)
* Server auth using Basic with user 'api'
> POST /api/v2/products/244/skus HTTP/1.1
Authorization: Basic BLAHBLAHBLAH=
Host: www.myhost.com
Accept: application/json
Content-Type: application/json
Content-Length: 181
Expect: 100-continue

< HTTP/1.1 100 Continue   ### hangs here for about 30 seconds, then...
* Empty reply from server
* Connection #0 to host www.myhost.com left intact
CURL EXEC DONE
```

Anyone else having this problem?  Can anyone create SKUs successfully?

**Comment by aleachjr** [comment]
Are you still experiencing this issue? We are able to successfully create SKUs using the client.

**Comment by Lewiscowles1986** [comment]
This is an issue we come up against as well, could aleachjr post some testing code so we can see if we are mis-using the API or mis-understanding

**Comment by mullinsr** [comment]
Have you tried using just the generic method?
```
$newSku = array(
    'sku' => '12345', //required
    'options' => array( //also required
        'product_option_id' => '25',
        'option_value_id' => '12'
        )
    );
Bigcommerce::createResource('/products/{product_id}/skus', $newSku);
```
https://developer.bigcommerce.com/api/stores/v2/products/skus#create-a-product-sku
Also, try calling `print_r(Bigcommerce::getLastError());` to get a response from BC. 

Let me know if that works, I just wrote it on the fly

**Comment by Lewiscowles1986** [comment]
lol it definitely looks different to our code although it looks like we create the option too... will test in the new week
