### ISSUE TITLE
updateOrder

### ISSUE THREAD

**Issue by pliebig** [bigcommerce/bigcommerce-api-php#107]
In your documentation / example php for orders you write something like 

require 'vendor/autoload.php';
    use Bigcommerce\Api\Client as Bigcommerce;

    Bigcommerce::configure(array(
    'store_url' => 'https://store-xxx.mybigcommerce.com',
    'username' => 'admin',
    'api_key' => 'xxxxxx'
    ));
    Bigcommerce_Api::setCipher('RC4-SHA')
    Bigcommerce_Api::verifyPeer(false);

    $order = array('status_id' => 1);
    Bigcommerce::updateOrder(110, $order);

but updateOrder does not exist.... pls keep your stuff up2date, currently this api is more a mess than really helpful for developers...

**Comment by aleachjr** [comment]
Thank you for the feedback. While updating orders is already possible, an update will be released in the very near future that includes adding the updateOrder() method to the client.
