### ISSUE TITLE
Get OptionSetOption

### ISSUE THREAD

**Issue by mshs013** [bigcommerce/bigcommerce-api-php#114]
How can I get OptionSetOption in bigcommerce PHP API?

**Comment by mullinsr** [comment]
To get all the options for a specific option set, do: <br>
```
use Bigcommerce\Api\Client as bc;

$id = 1; //The option set ID you wish to obtain options for. 
$options_list = bc::getResource('/optionsets/' .$id .'/options');
//print_r($options_list);
```
So then the URL for options, given the ID for the option set is: 
/optionsets/ID/options

This might help:
https://developer.bigcommerce.com/api/stores/v2/option_sets
https://developer.bigcommerce.com/api/stores/v2/options

**Comment by mshs013** [comment]
I use this before but it did not work :( @mullinsr

**Comment by mullinsr** [comment]
Well it does work, I just tested it. Please note that the ID for the option set may NOT start at 1. 
Are you able to connect to the store at all? 

Here's a full script for your convenience to print the options for the first 50 option sets, I am using the single bigcommerce.php library
```
<?php
require 'bigcommerce.php';
use Bigcommerce\Api\Client as bc;

bc::configure(array(
'store_url' => 'https://store-xxxxxxx.mybigcommerce.com',
'username' => 'xxxxx', //this all needs to be replaced with oAuth
'api_key' => 'xxxxxx'
));

bc::verifyPeer(false);
bc::setCipher('RC4-SHA');

$option_sets = bc::getOptionSets();

foreach($option_sets as $os)
{
  echo "Printing the options for Option Set: $os->name \n";
  print_r(bc::getResource('/optionsets/' .$os->id .'/options'));
}
```
Hope this helps.

**Comment by mshs013** [comment]
This works but I can not get optionset options into foreach function. It shows when I use print_r but it does not show in foreach function. Please help :( @mullinsr

**Comment by mullinsr** [comment]
I'm not sure what you're asking man, sorry :(

On line 700 of bigcommerce.php, change $fields from protected to public, if you are having trouble accessing specific data.

Maybe you mean this?
```
$optionSets = bc::getOptionSets();
foreach ($optionSets as $optionSet){
  $options = bc::getResource('/optionsets/' .$optionSet->id .'/options');
  foreach ($options as $option){
    //do something with each individual option
    }
  }
```

Remember this will only return the first 50 results.

**Comment by aleachjr** [comment]
I believe the issue is trying to retrieve a single resource when you want collection. The following code produces what you are looking for:

```
$optionSets = Bigcommerce::getOptionSets();
foreach ($optionSets as $optionSet){
    $options = Bigcommerce::getCollection('/optionsets/' .$optionSet->id .'/options');
    foreach ($options as $option){
        //do something with each individual option
        var_dump($option);
    }
}
```
