### ISSUE TITLE
Missing bigcommerce.php file?

### ISSUE THREAD

**Issue by mbphsong** [bigcommerce/bigcommerce-api-php#118]
Maybe I'm confused...I'm new to APIs and trying to download the files to connect to the BigCommerce API, but the master .zip I downloaded on GitHub didn't have a BigCommerce.php file in it anywhere.  Am I missing something on how to actually include this in my .php file so that I can access the API?

**Comment by aleachjr** [comment]
Please confirm that you are using the latest stable release version here https://github.com/bigcommerce/bigcommerce-api-php/releases/tag/2.0.7

We are working on a new beta version of the client that will no longer include bigcommerce.php. Moving forward, we will require apps to pull in the client dependency via composer.
