### ISSUE TITLE
API Connection issue

### ISSUE THREAD

**Issue by ssmcleod** [bigcommerce/bigcommerce-api-php#12]
Hi,

I have downloaded the bigcommerce API and created a test script using the get time sample.
I get the following error whenever trying to connect:

PHP Fatal error:  Class 'Bigcommerce_Api_Connection' not found in /sm/Bigcommerce/Api.php on line 120

Fatal error: Class 'Bigcommerce_Api_Connection' not found in /sm/Bigcommerce/Api.php on line 120

My test code is just:

<?php

require_once 'Bigcommerce/Api.php';

Bigcommerce_Api::configure(array(
    'store_url' => 'https://storeurl.mybigcommerce.com/api/v2/',
    'username'  => 'apiusername',
    'api_key'   => 'token'
));

$ping = Bigcommerce_Api::getTime();

if ($ping) echo $ping->format('H:i:s');
?>

Can you assist as to why this error occurs?

**Comment by aleachjr** [comment]
This appears to have been resolved some time back, closing.

**Comment by Lewiscowles1986** [comment]
Just to confirm that this still isn't fixed in the latest packagist version when attempting to update an order status to existing status. We've patched our code to be smarter, but the bug is still there.
