### ISSUE TITLE
getProductImages only pulls one image per product

### ISSUE THREAD

**Issue by mbphsong** [bigcommerce/bigcommerce-api-php#122]
I would expect that "getProductImages" for a given product id would give me multiple images, but it only pulls one for each product id.  If I use straight BigCommerce API connection and call /api/v2/products/{id}/images.json, I get more than one image per product id.

**Comment by mbphsong** [comment]
Changing "getResource" to "getCollection" in the public static function should fix it.

**Comment by aleachjr** [comment]
I was taking a look as well and agree. Will make this change tomorrow and merged into the 3.0 beta release on Monday.

**Comment by aleachjr** [comment]
Looks like we already addressed this last week (https://github.com/bigcommerce/bigcommerce-api-php/blob/master/src/Bigcommerce/Api/Client.php)
