### ISSUE TITLE
Order + coupon

### ISSUE THREAD

**Issue by cfv1000** [bigcommerce/bigcommerce-api-php#144]
Hello,

I'd like an example of applying a coupon on an order. 

Something like 

```

$order = BC::getOrder($id);
$order->setCoupon($coupon_id);

```

How can i achieve something similar?

Thanks

**Comment by mullinsr** [comment]
According to the <a href="https://developer.bigcommerce.com/api/stores/v2/orders"> docs </a>
```
"The Orders resource currently does not support coupon redemptions and discounts apart from 
manual discount"
```

So then you can either create or update the order with the `discount_amount` field like so:
`bc::updateOrder($id, array('discount_amount' => $discount_amount));`

**Comment by Paiman-Rasoli** [comment]
@sudosoul The approach you have mentioned is really great but the problem is how to update the `num_uses`? as I read the documentation even if we are not able to update that field using Coupon API as it is a read only field.
