### ISSUE TITLE
Issue updating/adding images

### ISSUE THREAD

**Issue by ssmcleod** [bigcommerce/bigcommerce-api-php#15]
Hi,

I am trying to add an image URL to a product.  I am using the following php code, but get nothing in return.
If I use the same code to update a product but remove the 'images' bit, it works fine.

$fields = array( "product_id" => "$prodid", "images" => array("image_file" => "$image"));
$apiresult=BigCommerce_Api::updateProduct($prodid, $fields);

**Comment by aleachjr** [comment]
Closing as no response in 2+ years. Please open another issue if you are still encountering issues.
