### ISSUE TITLE
Handshake Error...

### ISSUE THREAD

**Issue by Lewiscowles1986** [bigcommerce/bigcommerce-api-php#153]
So this AM we started getting the message
```
Fatal error: Uncaught exception 'Bigcommerce\Api\NetworkError' with message 'error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure' in 
```

**Comment by Lewiscowles1986** [comment]
Looks like this might be a PHP issue, although I am a little unsure if it is due to PHP, CURL, or BigCommerce rejecting SSLv3 requests

the remittance for me has been to use `TLSv1` as the Cipher ALA [Stackoverflow](http://stackoverflow.com/questions/28622558/how-to-solve-error-ssl23-get-server-hellosslv3-alert-handshake-failure)

**Comment by mullinsr** [comment]
Can you paste the output of the following from the cli:
```
openssl version -v
curl --version
```

**Comment by Lewiscowles1986** [comment]
```
$:~# openssl version -v
OpenSSL 1.0.1e 11 Feb 2013
```

```
$:~# curl --version
curl 7.26.0 (x86_64-pc-linux-gnu) libcurl/7.26.0 OpenSSL/1.0.1e zlib/1.2.7 libidn/1.25 libssh2/1.4.2 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp
Features: Debug GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP
```

**Comment by Lewiscowles1986** [comment]
It's worth noting the same server was working even earlier today, hence me asking if this is a BigCommerce policy to block SSLv3 requests. In any case I thought it best to leave the data in the issue when I closed as that way others can search and remit

**Comment by mullinsr** [comment]
**on a non-production environment**

Try the fix you mentioned in your StackOverflow link first... insert that into the `__construct()` of Connection.php:
```
function __construct() {
  curl_setopt($this->curl, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');
}
```

If that fails, try updating your version of openssl, and then even curl if all else. 
It was my understanding that sslV3 has been disabled for quite some time on BC, but maybe it didn't affect the api.

**Comment by Lewiscowles1986** [comment]
I'm not sure you have read the issue, maybe it is unclear

> the remittance for me has been to use TLSv1 as the Cipher ALA Stackoverflow

I am using TLSv1, luckily I have a GUI to set it in, I just thought this needs to be documented for BigCommerce :wink:

**Comment by mullinsr** [comment]
Ah yes, the error indicates the handshake failed due to the server rejecting your request cipher (sslv3). 

Either way, sslv3 is unsafe and deprecated for the past year now, it should not be used at all, and could be avoided with an updated version of openssl. 

Glad to hear you implemented the solution.

**Comment by aleachjr** [comment]
I would recommend for you to upgrade to the latest client version here (https://github.com/bigcommerce/bigcommerce-api-php/releases/tag/3.0.0). This was released back in June, and not only addresses a bunch of client issues, but also includes some clean up the security side. 

As for your specific experiences this morning, Bigcommerce has been working to remove unsafe ciphers. As of today, RC4 is no longer supported. Be sure to keep an eye on https://developer.bigcommerce.com as this type of information is posted here to inform developers of upcoming changes, prior to being rolled out.

<img width="1190" alt="screen shot 2015-09-24 at 6 11 58 am" src="https://cloud.githubusercontent.com/assets/3844269/10074222/682908c6-6283-11e5-8b8a-98dad3eb489b.png">

Please feel free to reach out to me directly at anthony.leach@bigcommerce.com if you need further assistance with this issue.

**Comment by Lewiscowles1986** [comment]
:+1: @mullinsr & @aleachjr 

@aleachjr is there a more optimal way to receive updates on these issues before they become ops issues?
