### ISSUE TITLE
brands filtering

### ISSUE THREAD

**Issue by mangesh12** [bigcommerce/bigcommerce-api-php#16]
Hi,

I am fetching brands from bigcommerce store through php api , but now i want to sort my brand in asseceding order  by brand name .....
I am using php api to fetch brands and my code is as below : 

$brands = BigCommerce_Api::getBrand($filter=false);

how can i get my brands in alphabetic order ?

**Comment by aleachjr** [comment]
Closing as no response in 2+ years. Please open another issue if you are still encountering issues.
