### ISSUE TITLE
APi Version 3 Support

### ISSUE THREAD

**Issue by oseintow** [bigcommerce/bigcommerce-api-php#183]
When are you supporting the version 3 of the api?

**Comment by bookernath** [comment]
Hey @oseintow, for the moment we're recommending auto-generating a client for a given V3 resource from the swagger documentation for that resource. As an example, the v3 catalog spec here: https://github.com/bigcommerce/api/blob/master/swagger/v3-catalog.yaml

Can be used to auto-generate an API client here: http://editor.swagger.io/

By using the "auto-generate client" function at the top.

Let us know if you have feedback on this process!

**Comment by Gemorroj** [comment]
@bookernath where it is now possible to take a configuration for swagger?
