### ISSUE TITLE
Typo in SKU Update URL

### ISSUE THREAD

**Issue by nschiffelbein** [bigcommerce/bigcommerce-api-php#219]
### Expected behavior
Calling BigCommerce::updateSKU($id, [....]) should update the given SKU variant on BigCommerce.

### Actual behavior
The call errors out because the URL referenced by this function has a typo in it, it currently reads /product/skus and it should read /products/skus

### Steps to reproduce behavior
Call the function, it always errors.

**Comment by lord2800** [comment]
Want to be a contributer? I'll review and get this merged ASAP if you want. Otherwise, I can tackle this on Monday.

**Comment by nschiffelbein** [comment]
No thanks, I was using the library in a project and ran into this issue while developing. I worked around it by calling the updateResource function directly (thanks for keeping that a public function, too many libraries protect/private their core API call functions preventing coders from working around bugs like this). Keep up the great work!

**Comment by optomal7** [comment]
Fixed in commit: 32318297a7d417107c673e23f27bdd4a7c1dd4e0
