### ISSUE TITLE
Add header to request

### ISSUE THREAD

**Issue by mgilpin** [bigcommerce/bigcommerce-api-php#31]
I can't figure out how to add a header to a request. For example: If-Modified-Since. It would be nice to retrieve orders by setting a min_date_created filter and then If-Modified-Since in the header to further limit the results without having to iterate over the results checking the value of 'date_modified' for each order.

**Comment by aleachjr** [comment]
We will be pushing an upcoming update which will allow you to set headers on the request similar to the following:

```
Bigcommerce::getConnection()->addHeader('header', 'value');

$options = Bigcommerce::getSkus();
```
