### ISSUE TITLE
HTML posting

### ISSUE THREAD

**Issue by Lewiscowles1986** [bigcommerce/bigcommerce-api-php#39]
If I post HTML to a product description (Useful for allowing me to add YouTube video's regardless of API support) then they come through great on my BigCommerce Store. So this is a valid workaround for adding video's IMHO.

If however I try to edit the product from within BigCommerce Admin Back-End, then it rather un-helpfully fixes the markup for me (I am posting broken markup so that I can add accordion Items such as YouTube, and to break up content to make the product pages more readable and user-friendly)

Please provision for an API option to stop BigC "Helping" with content, even a button to stop it fixing DOM errors would be great.

**Comment by aleachjr** [comment]
Closing as this is an unsupported feature.
