### ISSUE TITLE
Products not all adding...

### ISSUE THREAD

**Issue by Lewiscowles1986** [bigcommerce/bigcommerce-api-php#41]
Hi Products are not adding to categories all the time and out of say 73 products I am only getting 55... This is a little worrying as the error is that the product cannot be added to the category due to a resource conflict. These Products are being created, automatically added to the New category (which exists) as well as any other categories we have it mapped to using the category ID's provided by the API...

Worth noting using CSV import even less products get added, which is again... troubling...

**Comment by aleachjr** [comment]
If this is still an issue can you please provide details of the client calls you are using?

**Comment by Lewiscowles1986** [comment]
Unfortunately with a store to run the store owner decided to use your back-end instead, this was a long time ago so I shall close. Thanks for adding more activity here than any others in a long time though :+1:

**Comment by aleachjr** [comment]
Please feel free to contact me directly if you encounter any issues with the client. We will be releasing a new beta client very soon. Thank you again!
