### ISSUE TITLE
Coupon bug - POST returns "ID" error

### ISSUE THREAD

**Issue by ransomcarroll** [bigcommerce/bigcommerce-api-php#43]
Doing a post method to create a new coupon is returning this error:

[{"status":400,"message":"The field 'id' cannot be written to. Please remove it from your request before trying again."}]

Its important to note that no ID field was provided in the JSON object. Basic examples were used from the Bigcommerce quickstarts section as well as our own new objects. All fail as it appears to be asserting a false positive for an ID within the object.

**Comment by aleachjr** [comment]
I am able to create coupons using the following code:

```$coupon = array(
    'name' => 'somecoupon',
    'type' => 'percentage_discount',
    'amount' => 50,
    'code' => '50off',
    'enabled' => true,
    'applies_to' => array(
        'entity' => 'products',
        'ids' => array(32)
    )
);

$c = Bigcommerce::createCoupon($coupon);```

This appears to be working at this time, please open another issue if you continue to experience issues.
