### ISSUE TITLE
Bigcommerce product update API

### ISSUE THREAD

**Issue by pavanjb** [bigcommerce/bigcommerce-api-php#44]
I am using bigcommerce API to update product inventory values . There are about 3000 products to be updated.. With API a few hundred gets updated but after that it gives "could not connect to host". I am using same code on github which bigcommerce has provided. please help

Is there some kind of throttlelimit for bigcommerce product updation. ?

Please let me know

**Comment by aleachjr** [comment]
Closing as there has been no response over the last year. Please open another issue if you continue to experience issues.
