### ISSUE TITLE
GET selected OPTIONS for a OPTION_SET linked to a PRODUCT

### ISSUE THREAD

**Issue by nikhil-bhandari** [bigcommerce/bigcommerce-api-php#45]
I am using the API to get the Option Sets associated with a particular product.

At the back-end here's how things go.
1. Add an Option Set
![createoptionsets](https://f.cloud.github.com/assets/3707482/498186/589a148a-bc0f-11e2-8f1b-f717244465d2.png)
2. Add Option
3. Select Option Values
![selectoptionvalues](https://f.cloud.github.com/assets/3707482/498187/58a1b320-bc0f-11e2-8ece-05a0b1840b5d.png)

Now I am trying to figure out how to get the option values that are selected in step 3, but I cannot find any resource where anything about this is documented. I am not even sure if the API offers this functionality.

The current flow that I am using is

    product -> option_set -> option -> option_values

This gives all the options available and not the ones that are selected.

    Necklace -> someOptionSetName -> length -> {16, 17, 18, 19,  20, 21, 22, 23,  24}

 What I want is 

    product -> option_set -> option -> selected_option_values ->option_values

ie.

    Necklace -> someOptionSetName -> length -> {16,  20, 24}

So am I missing something? or the API doesn't support this?

**Comment by aleachjr** [comment]
Appears resolved, closing.
