### ISSUE TITLE
Getting problem in configuring  bigcommerce-api-php

### ISSUE THREAD

**Issue by rose4jyoti** [bigcommerce/bigcommerce-api-php#48]
I have followed the all instruction in read me file.

1) download file from here (https://raw.github.com/bigcommerce/bigcommerce-api-php/master/bigcommerce.php )single file.

2) Put inside folder Bigcommerce like Bigcommerce/bigcommerce.php

3) require 'Bigcommerce/bigcommerce.php

4) write this code in my big.php file

require_once 'BigCommerce/bigcommerce.php';
Bigcommerce::configure(array(
'store_url' => 'https://store.mybigcommerce.com',
'username' => 'admin',
'api_key' => 'd81aada4c19c34d913e18f07fd7f36ca'
));

now getting error Class 'Bigcommerce' not found etc.

Please let me know if I am missing something.

In readme file there is one more line : To use the API client in your PHP code, ensure that you can access Bigcommerce\Apiin your autoload path (using Composer’s vendor/autoload.php hook is recommended).

is it required how to configure this?

I am getting nothing blank page is coming.

**Comment by aleachjr** [comment]
This appears to have been a configuration issue and resolved, closing.
