### ISSUE TITLE
Images uploaded via api loose their filename

### ISSUE THREAD

**Issue by Lewiscowles1986** [bigcommerce/bigcommerce-api-php#51]
For some reason when upoaded to the CDN via the BigCommerce API the images loose their file names, this is interfering with a plugin by scriptilabs, who I am told are a bigcommerce developer...

**Comment by aleachjr** [comment]
Please confirm if this is still an issue so we can address.

**Comment by Lewiscowles1986** [comment]
Unknown, doesn't affect client as we don't filter images using JS any more and don't use product options any more either.
