### ISSUE TITLE
$order->products()

### ISSUE THREAD

**Issue by watermark** [bigcommerce/bigcommerce-api-php#53]
"/orders/{orderId}/products.json" seems to have an undocumented api for limit.  As it is now, $order->products() will only return 50 line items, even if there are more than that on the order.

I propose:
Adding a param to $order->products() so you can specify a new limit

editing the BigCommerce API documentation to reflect that there is a limit variable and by default it caps at 50.

**Comment by aleachjr** [comment]
Closing this issue as there has been no discussion in 2+ years. I do see there is an open PR, will review in the next few days.

**Comment by watermark** [comment]
This issue remains unresolved.  This issue only affects orders with more than 50 different products.  We do have orders like this on occasion.

**Comment by mullinsr** [comment]
hi watermark!

i just wanted to chime in say that i believe it is possible to increase the limit on this resource by constructing your own API request, with the filter manually applied in the request URI. 

What i mean by that is:
```
/orders/{order_id}/products?limit=250
```
or, specifically, with this library:
```
require 'autoload.php';
use Bigcommerce\Api\Client as bc;
$orderProducts = bc::getResource('/orders/{order_id}/products?limit=250');
// or it  might be --> bc::getCollection('/orders/{order_id}/products?limit=250');
```

although this doesn't solve the issue with the library itself, i hope this finds you well as a solution in the meantime. please let me know if i am mistaken or if i should clarify. thx :-)

**Comment by watermark** [comment]
Can this issue be reopened?

**Comment by elykinnovation** [comment]
I created a way to pull all orders from a BigCommerce store no matter how many pages at 250 limit per page: Hope someone finds it useful. It uses the v3 API method and classes etc...

`// include needed api files
require($_SERVER['DOCUMENT_ROOT'] . '/path/to/vendor/autoload.php'); // change me
use Bigcommerce\Api\Client as Bigcommerce;

// make the connection OAuth style
Bigcommerce::configure(array(
	'client_id' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx', // CLIENT ID
	'auth_token' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx', // ACCESS TOKEN
	'store_hash' => 'xxxxxxxxxx' // STORE ID
));

// orders
$orders_count = Bigcommerce::getOrdersCount();
$orders_pages = ceil($orders_count / 250);
$orders = array();
for ($o=1; $o <= $orders_pages; $o++) {
	$orders = array_merge(
		$orders,
		Bigcommerce::getOrders(
			array(
				'page' => $o,
				'limit' => '250',
			)
		)
	);
}`

then you can simply use a foreach to run thru all orders for any purpose you may have :)

`foreach ($orders as $i => $order) { // do stuff }`
