### ISSUE TITLE
updateOrder() function not found

### ISSUE THREAD

**Issue by derek-b** [bigcommerce/bigcommerce-api-php#57]
According to the PHP quickstart documentation at http://developer.bigcommerce.com/quickstarts/php there should be a function updateOrder() which takes in an id and a parameter array.  However, I cannot find this function in Bigcommerce\Api\Client.php.

**Comment by aleachjr** [comment]
I am unable to locate the documentation you are referring to but can confirm that there is no updateOrder() function in the client. I would suggest getting an order object, making your desired changes, and then calling $order->update(). This should have the desired results.
