### ISSUE TITLE
Configuring Issue

### ISSUE THREAD

**Issue by utpal4job** [bigcommerce/bigcommerce-api-php#68]
Hello, I have installed composer.phar on "httpdocs" folder. I have uploaded all the bigcommerce files under "bigcommerce" folder and this folder is exits under "httpdocs" folder. I have also setup the store url with api token on "index.php" file but when running the file then nothing is displaying on the page.

Please help me how to solve this issue. 

Regards.

**Comment by aleachjr** [comment]
This appears to be a configuration issue. If you are still experiencing, please open a new issue.
