### ISSUE TITLE
Updating orders error line 960 on bigcommerce.php

### ISSUE THREAD

**Issue by IDtech** [bigcommerce/bigcommerce-api-php#76]
FYI, we had an issue updating orders->staff_notes, but kept getting...

Fatal error: Class 'Bigcommerce\Api\Resources\stdClass' not found in /home/thedevon/public_html/bigcommerce.php on line 960

Which is ...

$order = new stdClass();

We changed it to ...

$order = new \stdClass;

And now works fine.

**Comment by aleachjr** [comment]
Thank you for the update.
