### ISSUE TITLE
Customer Accepts Email Marketing

### ISSUE THREAD

**Issue by ghost** [bigcommerce/bigcommerce-api-php#78]
When a customer places an order on BigCommerce they're able to state whether they wish to receive email marketing.

Is it possibly, or could it be possible, to retrieve this value from the api?

I'm not sure whether this would need to be part of the customer api or the order api, but would definitely be handy either way.

Thanks.

**Comment by aleachjr** [comment]
Closing this issue as there is nothing else to discuss in this issue. The information has been relayed to appropriate product managers.
