### ISSUE TITLE
Creating Parent Categories

### ISSUE THREAD

**Issue by eMatsiyana** [bigcommerce/bigcommerce-api-php#79]
I have the Code below to create a category which works fine,
But i also need to create a Parent category ..

What's the best way to do that?

 $CategoryName ="child_cat";
$mycategory = array('name' =>$CategoryName, 'search_keywords' =>$CategoryName , 'is_visible' => true);

Bigcommerce::createCategory($mycategory);

And if i want to create another Parent Category for that, is it possible and how?

**Comment by aleachjr** [comment]
This appears to be resolved, closing.
