### ISSUE TITLE
Api\Connection put() method "Too many open files" error.

### ISSUE THREAD

**Issue by dbetts** [bigcommerce/bigcommerce-api-php#80]
The file handle needs to be closed after each call to the put() method, otherwise the calling server will eventually run out of resources if the same cURL initialization variable is being used over and over for multiple requests inside the same session.

Simply add the following to the end of the method:

curl_exec($this->curl);

fclose($handle); // DSB Added this line
curl_setopt($this->curl, CURLOPT_INFILE, STDOUT); // DSB Added this line

return $this->handleResponse();

**Comment by aleachjr** [comment]
This has already been addressed in an upcoming release.
