### ISSUE TITLE
Suggestion: Add Shipments capability

### ISSUE THREAD

**Issue by billda** [bigcommerce/bigcommerce-api-php#9]
At the moment, there is no capability in the library to add shipments to orders (e.g. /orders/101/shipments). I've built the rest of my integration with this library, but needed to create shipments with cURL - not ideal, especially because I think confirming products shipped is probably a fairly common use case.

**Comment by aleachjr** [comment]
This has been added in the latest Beta release: https://github.com/bigcommerce/bigcommerce-api-php/releases/tag/3.0.0-beta.8
