### ISSUE TITLE
Products return empty 

### ISSUE THREAD

**Issue by orthoworld** [bigcommerce/bigcommerce-api-php#90]
I am trying to implement this  into codeigniter like so:

                   $this->load->library('client/connection');
                   $this->load->library('client/client');
                   $this->load->library('client/filter');
                   $this->load->library('client/product');
                   $this->load->library('client/Resource');
                   $this->load->library('client/Order');
                   $this->client->configure(array(
                      'store_url' => 'https://store-fuh8f4r.mybigcommerce.com/api/v2/',
                      'username' => 'escott',
                      'api_key' => '75dff2b3121f65cf201e9eebd421e3d899f80f92'
                      ));
         
                    $this->client->configure(array(
                      'store_url' => 'https://store-fuh8f4r.mybigcommerce.com/api/v2/',
                      'username' => 'escott',
                      'api_key' => '75dff2b3121f65cf201e9eebd421e3d899f80f92'
                   ));
                  $products = $this->client->getProducts();

                    foreach($products as $product) {
                        echo"<pre>";
                        print_r($product);
                        echo"</pre>";
                    }
                  
                   $ping = $this->client->getTime();
                   if ($ping) 
                  {
                        echo $ping->format('H:i:s');
                   }
                

The time is returned, so I think the connection is successful, however, none of the products will return. I'll only get this:

     Product Object
    (
    [ignoreOnCreate:protected] => Array
        (
            [0] => date_created
            [1] => date_modified
        )

    [ignoreOnUpdate:protected] => Array
        (
            [0] => id
            [1] => rating_total
            [2] => rating_count
            [3] => date_created
            [4] => date_modified
            [5] => date_last_imported
            [6] => number_sold
            [7] => brand
            [8] => images
            [9] => discount_rules
            [10] => configurable_fields
            [11] => custom_fields
            [12] => videos
            [13] => skus
            [14] => rules
            [15] => option_set
            [16] => options
            [17] => tax_class
        )

    [ignoreIfZero:protected] => Array
        (
            [0] => tax_class_id
        )

)

**Comment by aleachjr** [comment]
I have confirmed that this is currently working on a local store. If you are still experiencing this, please open new issue.
