### ISSUE TITLE
Bug on the Sku class

### ISSUE THREAD

**Issue by ccovey** [bigcommerce/bigcommerce-api-php#92]
For the following call:

`$options = Client::getCollection($this->fields->options->resource, 'SkuOption');`

the options field is an array and doesn't contain any resource property. It looks like the following:

`array(1) {
  [0] =>
  class stdClass#6367 (2) {
    public $product_option_id =>
    int(1)
    public $option_value_id =>
    int(1)
  }
}`

**Comment by yingliangzhang** [comment]
Same problem here, this is a bug. Please fix

**Comment by bc-sandeep** [comment]
this would be great to fix

cc @ICarpenter @zvuki

**Comment by zvuki** [comment]
cc @becomevocal

**Comment by zvuki** [comment]
Fixed https://github.com/bigcommerce/bigcommerce-api-php/releases/tag/3.0.1
