### ISSUE TITLE
No support for updating products to categories

### ISSUE THREAD

**Issue by osakagreg** [bigcommerce/bigcommerce-api-php#93]
IAs an example, in an instance such as:

Bigcommerce::updateProduct($product->id, $fields);

Where $fields is:
Array
(
    [categories] => Array
        (
            [0] => 43
            [1] => 154
            [2] => 5806
        )

)

Quite often this results in a 409 error:
Uncaught Client Error (409): A resource conflict prevented the request from being fulfilled.

I have noticed it mainly when a product is attempting a consecutive update.

For example:
Array
(
    [categories] => Array
        (
            [0] => 43
            [1] => 154
            [2] => 5806
        )

)
then on the same product id in the same loop:
Array
(
    [categories] => Array
        (
            [0] => 43
            [1] => 154
            [2] => 5806
            [3] => 5824
        )

)

Is there a better way to update products to categories?  Or a way to bypass the 409?

**Comment by aleachjr** [comment]
Appears resolved, closing.

**Comment by vipin12117** [comment]
It is not solved yet. still getting errors

Product: A resource conflict prevented the request from being fulfilled for APSR86300H
Category: A resource conflict prevented the request from being fulfilled for Avenger 1222
