### ISSUE TITLE
Create customer password

### ISSUE THREAD

**Issue by Zigii** [bigcommerce/bigcommerce-api-php#94]
Hi, trying to use Bigcommerce API (PTP) to create new customer. See my code below.

Code is working fine EXCEPT that I don't seem to be able to create customer password. 

I don't fully understand the authentication process so my code that reads:
'_authentication'=>$authentication
is probably wrong.

Could anyone help me?  

require_once "bigcommerce-api/bigcommerce.php";

use Bigcommerce\Api\Client as Bigcommerce;

Bigcommerce::configure(array(
'store_url' => 'https://store-xxxxxxxx.mybigcommerce.com/',
	'username'  => 'admin',
    'api_key'   => 'xxxxxxxxxxxxxxxxxxxxx'
));

Bigcommerce::setCipher('RC4-SHA');
Bigcommerce::verifyPeer(false);

$first_name = $contact_1_firstname_san;
$last_name = $contact_1_lastname_san;
$email = $contact_1_email_san;
$company = $company_trading_name_san;
$phone = $contact_1_phone_san;
$store_credit = "0";
$customer_group_id = "2";
$authentication = $password_1_san;

$createFields = array('first_name'=>$first_name,'last_name'=>$last_name,
'email'=>$email, 'company'=>$company,'phone'=>$phone,
'store_credit'=>$store_credit,'customer_group_id'=>$customer_group_id,
'_authentication'=>$authentication);

$customers = Bigcommerce::createCustomer($createFields);

**Comment by aleachjr** [comment]
Authentication should not just contain the password. See the following: https://developer.bigcommerce.com/api/stores/v2/customers#create-a-customer
