### ISSUE TITLE
getOrdersCount has issue

### ISSUE THREAD

**Issue by Lewiscowles1986** [bigcommerce/bigcommerce-api-php#98]
Hi getOrdersCount has some issues

Firstly I can use the function and it works to return a count

BUT...
because it seemed to not support the filters listed on the API page I used getBrandsCount syntax to rewrite it

    public static function getOrdersCount()
    {
        return self::getCount('/orders/count');
    }

Became 

    public static function getOrdersCount($filter = false)
    {
        $filter = Filter::create($filter);
        return self::getCount('/orders/count' . $filter->toQuery());
    }

It seemed logical as I have checked with other functions, but this just does not alter the count. Please fix this as our mutual client is understandably annoyed that after 1 year the API is still coming back with so many issues and we are having to hot-fix things...

**Comment by aleachjr** [comment]
Thank you for the feedback. This has been added to an upcoming release.
