### ISSUE TITLE
Unable to add order notes / comments via PHP API

### ISSUE THREAD

**Issue by Lewiscowles1986** [bigcommerce/bigcommerce-api-php#99]
we try updating the order notes via API but we never get an error and the notes never update

**Comment by aleachjr** [comment]
Thank you for the feedback. We will be releasing an update in the very near future that includes a fix to updating orders. You will be able to do something similar as below:

```
$filter = array('staff_notes' => 'staff notes');

Bigcommerce::updateOrder(100, $filter);

$u = Bigcommerce::getOrder(100);
var_dump($u);
```

**Comment by Lewiscowles1986** [comment]
good this is pretty much what we are doing anyway...

**Comment by Lewiscowles1986** [comment]
@aleachjr should the code above work now, or do you have an ETA?

**Comment by mullinsr** [comment]
Here's a snippet of a program in production we have responsible for updating order notes:
```
//** Define The Order ID Here **//
$id = 123;

//** Create the order message **//
$update = array(
    'staff_notes' => "Insert Your Order Note Here"
);

//** Update the order **//
$res = bc::updateResource("/orders/" .$id, $update);

//** Print The Response To Confirm Update **//
print_r($res);
```

**Comment by Lewiscowles1986** [comment]
:+1: @mullinsr

**Comment by aleachjr** [comment]
:+1:
